twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        application_name: '%application_name%'
        admin_contact_email: '%env(ADMIN_CONTACT_EMAIL)%'
        min_password_length: '%env(MIN_PASSWORD_LENGTH)%'
        recaptcha_sitekey: '%recaptcha_sitekey%'
        single_scan_price: '%single_scan_price%'
        single_scan_currency: '%single_scan_currency%'
        use_barcodes: '%env(USE_BARCODES)%'
        logo_image_file: '%env(LOGO_IMAGE_FILE)%'
        logo_image_width: '%env(LOGO_IMAGE_WIDTH)%'
        logo_image_height: '%env(LOGO_IMAGE_HEIGHT)%'


